# Generated by Django 5.1 on 2025-01-26 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_questionreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='question_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questions',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='question_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
